---
- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  vars:
    kubernetes_version: "1.27.4"  # Replace with your preferred Kubernetes version
    cilium_version: "1.13.0"
    control_ip: "{{ control_ip }}"
    pod_cidr: "10.244.0.0/16"  # Default Pod CIDR
    service_cidr: "10.96.0.0/12"  # Default Service CIDR
    config_path: "/tmp/kubeconfigs"

  tasks:
    - name: Install common packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Disable swap
      command: swapoff -a

    - name: Disable swap on reboot
      cron:
        name: "Disable swap"
        minute: "@reboot"
        job: "/sbin/swapoff -a"

    - name: Install Kubernetes tools
      apt:
        name:
          - kubelet={{ kubernetes_version }}
          - kubectl={{ kubernetes_version }}
          - kubeadm={{ kubernetes_version }}
        state: present

    - name: Initialize Kubernetes (Control Plane)
      command: kubeadm init --apiserver-advertise-address={{ control_ip }} --pod-network-cidr={{ pod_cidr }} --service-cidr={{ service_cidr }}
      when: inventory_hostname == 'controlplane'

    - name: Configure kubectl for vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: 0600
      when: inventory_hostname == 'controlplane'

    - name: Join Worker Nodes
      command: "{{ lookup('file', '/tmp/join.sh') }}"
      when: inventory_hostname != 'controlplane'

    - name: Install Helm
      shell: |
        curl -fsSL https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz -o helm.tar.gz
        tar -xzf helm.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Deploy Cilium with Helm
      command: |
        helm repo add cilium https://helm.cilium.io
        helm repo update
        helm install cilium cilium/cilium --version={{ cilium_version }} --namespace kube-system --set kubeProxyReplacement=strict
      when: inventory_hostname == 'controlplane'

    - name: Deploy Kubernetes Dashboard
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v{{ dashboard_version }}/aio/deploy/recommended.yaml
      when: inventory_hostname == 'controlplane'

